version: '3'
services:
  app:
    image: haggingface-sandbox
    build:
      context: .
      dockerfile: Dockerfile

    user: root
    tty: true

    ports:
      - "7860:7860"

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    command: python3 chatbot.py